Check for both possible orders of script output in tests

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -969,12 +969,23 @@ if [ $? != 0 ]; then
 	exit 3
 fi
 
+# Check both possible orders
+grep "test2.log.1" scriptout >/dev/null
+if [ $? != 0 ]; then
+	grep "test.log.1" scriptout >/dev/null
+	if [ $? != 0 ]; then
+		echo "ERROR: scriptout should contain 'test2.log.1' or 'test.log.1'"
+		exit 3
+	fi
+fi
+
+rm -f scriptout
+
 checkoutput <<EOF
 test.log 0
 test.log.1 0 zero
 test2.log 0
 test2.log.1 0 zero
-scriptout 0 test2.log.1
 EOF
 
 cleanup 40
