test we don't rotate on corrupted state files
Signed-off-by: Joern Engel <joern@logfs.org>

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -1111,5 +1111,33 @@ test.log 0 zero
 scriptout 0 
 EOF
 
+cleanup 46
+
+# ------------------------------- Test 46 ------------------------------------
+# the state file is truncated and obviously corrupt, so no rotation should
+# happen
+preptest test.log 46 1
+
+cat > state << EOF
+logrotate state -- version 1
+"$PWD/test.log" 2000-1-1
+"$PWD/test2.l
+EOF
+
+DATESTRING=$(/bin/date +%Y%m%d)
+$RLR test-config.46 2>error.log
+
+grep "error: bad line 3 in state file state" error.log >/dev/null
+if [ $? != 0 ]; then
+	echo "No error printed, but there should be one."
+	exit 3
+fi
+
+rm -f error.log
+
+checkoutput <<EOF
+test.log 0 zero
+EOF
+
 
 cleanup
