unit tests for missingok

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -476,7 +476,7 @@ fi
 
 cleanup 20
 
-# ------------------------------- Test 19 ------------------------------------
+# ------------------------------- Test 20 ------------------------------------
 preptest test.log 20 1
 $RLR test-config.20 --force 2>error.log
 
@@ -485,6 +485,42 @@ if [ $? == 0 ]; then
 fi
 
 grep "error running shared postrotate script for" error.log >/dev/null
+if [ $? != 0 ]; then
+	echo "No error printed, but there should be one."
+	exit 3
+fi
+
+cleanup 21
+
+# ------------------------------- Test 21 ------------------------------------
+# different base name, so it should not find the file
+preptest differenttest.log 21 1
+$RLR test-config.21 --force 2>error.log
+
+if [ $? != 0 ]; then
+	echo "Logrotate exited with non-zero exit code, but it should not"
+fi
+
+cat error.log
+
+# grep "error running shared postrotate script for" error.log >/dev/null
+# if [ $? != 0 ]; then
+# 	echo "No error printed, but there should be one."
+# 	exit 3
+# fi
+
+cleanup 22
+
+# ------------------------------- Test 22 ------------------------------------
+# different base name, so it should not find the file
+preptest differenttest.log 22 1
+$RLR test-config.22 --force 2>error.log
+
+if [ $? == 0 ]; then
+	echo "Logrotate exited with zero exit code, but it should not"
+fi
+
+grep "error: stat of" error.log >/dev/null
 if [ $? != 0 ]; then
 	echo "No error printed, but there should be one."
 	exit 3
