Added preremove option to let admin do something with the old logs before they are removed by logrotate

diff --git a/trunk/test/test b/trunk/test/test
--- a/trunk/test/test
+++ b/trunk/test/test
@@ -866,4 +866,40 @@ test.log.1 0 zero
 scriptout 0 second
 EOF
 
+cleanup 38
+
+# ------------------------------- Test 38 ------------------------------------
+# preremove script
+preptest test.log 38 1
+preptest test2.log 38 1
+$RLR test-config.38 --force 
+
+checkoutput <<EOF
+test.log 0
+test2.log 0
+scriptout 0 test2.log.1test.log.1
+EOF
+
+cleanup 39
+
+# ------------------------------- Test 39 ------------------------------------
+# preremove script error - do not remove log file
+preptest test.log 39 1
+preptest test2.log 39 1
+$RLR test-config.39 --force 2>error.log
+
+grep "error running preremove script" error.log >/dev/null
+if [ $? != 0 ]; then
+	echo "No error 'error running preremove script' printed, but there should be one."
+	exit 3
+fi
+
+checkoutput <<EOF
+test.log 0
+test.log.1 0 zero
+test2.log 0
+test2.log.1 0 zero
+scriptout 0 test2.log.1
+EOF
+
 cleanup
