Changelog update, new test for maxsize, maxsize fix

diff --git a/trunk/test/test b/trunk/test/test
--- a/trunk/test/test
+++ b/trunk/test/test
@@ -142,6 +142,7 @@ preptest() {
 # we don't want any stuff left from previous runs
 cleanup
 
+# ------------------------------- Test 1 -------------------------------------
 # Without a log file, no rotations should occur
 preptest test.log 1 2
 $RLR test-config.1 
@@ -176,6 +177,7 @@ EOF
 
 cleanup 1
 
+# ------------------------------- Test 2 -------------------------------------
 preptest test.log 2 3
 $RLR test-config.2 --force
 
@@ -203,6 +205,7 @@ EOF
 
 cleanup 3
 
+# ------------------------------- Test 3 -------------------------------------
 preptest test.log 3 1
 preptest test2.log 3 1
 $RLR test-config.3 --force
@@ -217,6 +220,7 @@ EOF
 
 cleanup 4
 
+# ------------------------------- Test 4 -------------------------------------
 preptest test.log 4 1
 preptest test2.log 4 1
 $RLR test-config.4 --force 
@@ -231,6 +235,7 @@ EOF
 
 cleanup 5
 
+# ------------------------------- Test 5 -------------------------------------
 preptest test.log 5 1
 preptest anothertest.log 5 1
 $RLR test-config.5 --force 
@@ -245,6 +250,7 @@ EOF
 
 cleanup 6
 
+# ------------------------------- Test 6 -------------------------------------
 preptest test.log 6 1
 preptest anothertest.log 6 1
 $RLR test-config.6 --force
@@ -259,6 +265,7 @@ EOF
 
 cleanup 7
 
+# ------------------------------- Test 7 -------------------------------------
 preptest test.log 7 1
 preptest anothertest.log 7 1
 
@@ -274,6 +281,7 @@ EOF
 
 cleanup 8
 
+# ------------------------------- Test 8 -------------------------------------
 preptest test.log 8 1 1
 $RLR test-config.8 --force
 
@@ -287,6 +295,7 @@ checkmail test.log zero
 
 cleanup 9
 
+# ------------------------------- Test 9 -------------------------------------
 preptest test.log 9 1 1
 $RLR test-config.9 --force
 
@@ -299,6 +308,7 @@ checkmail test.log zero
 
 cleanup 10
 
+# ------------------------------- Test 10 ------------------------------------
 preptest test.log 10 1
 $RLR test-config.10 --force
 
@@ -320,6 +330,7 @@ checkmail test.log.1 newfile
 
 cleanup 11
 
+# ------------------------------- Test 11 ------------------------------------
 preptest test.log 11 2 1
 $RLR test-config.11 --force
 
@@ -333,6 +344,7 @@ checkmail test.log first
 # check rotation into a directory given as a relative pathname
 cleanup 12
 
+# ------------------------------- Test 12 ------------------------------------
 preptest test.log 12 1 0
 rm -rf testdir
 mkdir testdir
@@ -348,6 +360,7 @@ rm -rf testdir
 # check rotation into a directory given as an absolute  pathname
 cleanup 13
 
+# ------------------------------- Test 13 ------------------------------------
 preptest test.log 13 1 0
 rm -rf testdir
 mkdir testdir
@@ -363,6 +376,7 @@ rm -rf testdir
 # sanity rotation check using dateext and dateformat
 cleanup 14
 
+# ------------------------------- Test 14 ------------------------------------
 preptest test.log 14 1 0
 
 $RLR test-config.14 --force
@@ -379,9 +393,8 @@ rm -rf testdir
 # shred test
 cleanup 15
 
+# ------------------------------- Test 15 ------------------------------------
 preptest test.log 15 1 0
-rm -rf testdir
-mkdir testdir
 $RLR test-config.15 --force
 
 # this rotation should use shred
@@ -392,6 +405,26 @@ test.log 0
 test.log.1 0
 EOF
 
-rm -rf testdir
+cleanup 16
 
-cleanup
+# ------------------------------- Test 16 ------------------------------------
+preptest test.log 16 1 0
+# log with 1 byte should not be rotated
+echo "a" > test.log
+$RLR test-config.16
+
+if [ -f test.log.1 ]; then
+	echo "file $file does exist!"
+	exit 2
+fi
+
+# log with 4 bytes should be rotated
+echo "zero" > test.log
+$RLR test-config.16
+
+checkoutput <<EOF
+test.log 0
+test.log.1 0 zero
+EOF
+
+# cleanup
