Sort glob results only when custom dateformat is used

diff --git a/trunk/test/test b/trunk/test/test
--- a/trunk/test/test
+++ b/trunk/test/test
@@ -766,7 +766,7 @@ preptest test.log 30 1 0
 DATESTRING=$(/bin/date +%Y%m%d)
 echo "one" > test.log-$DATESTRING
 
-$RLR test-config.30 --force -v
+$RLR test-config.30 --force
 checkoutput <<EOF
 test.log 0 zero
 test.log-$DATESTRING 0 one
@@ -1498,7 +1498,13 @@ cleanup 60
 preptest test.log 60 1
 echo test2 > test2.log
 
-$RLR test-config.60 -v
+$RLR test-config.60 2>error.log
+
+grep "error opening" error.log >/dev/null
+if [ $? != 0 ]; then
+	echo "No error printed, but there should be one."
+	exit 3
+fi
 
 checkoutput <<EOF
 test2.log 0
